---
site_name: Cyber Manufacturing
site_author: Santosh Ganji
copyright: Copyright &copy; Texas A&M

watch:
  - README.md
  - CHANGELOG.md
  - src/doc2dash/__main__.py
  - src/doc2dash/parsers/types.py

nav:
  - About: index.md
  - Dataset: quickstart.md
  - Using Read_the_doc: using_readthedocs.md
  - Learning Algorithms: mlalgos.md
  - Meta:
    - License & Credits: credits.md
  

theme:
  name: material
  features:
    - navigation.expand
    - navigation.sections
  font: false
  icon: docs/TAM-LogoBox.png
    repo: fontawesome/brands/github
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

extra_css:
  - stylesheets/extra.css

repo_url: https://github.com/shotsan/cybermanufacturing/
repo_name: Cyber Manufacturing
edit_uri: blob/main/docs

 

markdown_extensions:
  - admonition
  - smarty
  - attr_list
  - mkdocs-click
  - pymdownx.smartsymbols
  - footnotes
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
plugins:
  - search
  - callouts
  - include-markdown
  - mkdocstrings:
      handlers:
        python:
          paths: [src]
          import:
            - https://docs.python.org/3/objects.inv
